// Generated by Xata Codegen 0.29.5. Please do not edit.
import { buildClient } from "@xata.io/client";
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "tag",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "gallery" },
    ],
    revLinks: [{ column: "tag", table: "tag-to-image" }],
  },
  {
    name: "image",
    columns: [
      { name: "name", type: "string", notNull: true, defaultValue: "Image" },
      { name: "image", type: "file" },
    ],
    revLinks: [{ column: "image", table: "tag-to-image" }],
  },
  {
    name: "tag-to-image",
    columns: [
      { name: "image", type: "link", link: { table: "image" } },
      { name: "tag", type: "link", link: { table: "tag" } },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = buildClient();
const defaultOptions = {
  databaseURL:
    "https://stupienius-s-workspace-sca1um.ap-southeast-2.xata.sh/db/stu-database",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
export class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
let instance = undefined;
/** @type { () => XataClient } */
export const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
